apiVersion: v1
kind: ReplicationController
metadata:
  name: loadbalancer-daemon-rc
  labels:
    app: loadbalancer-daemon
spec:
  replicas: 1
  selector:
    app: loadbalancer-daemon
  template:
    metadata:
      labels:
        app: loadbalancer-daemon
    spec:
      hostNetwork: true
      containers:
      - image: kokhang/loadbalancer-daemon:0.1
        imagePullPolicy: Always
        name: loadbalancer-daemon
        ports:
        securityContext:
          privileged: true
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
