apiVersion: v1
kind: ReplicationController
metadata:
  name: loadbalancer-daemon-rc
  labels:
    app: loadbalancer-daemon
spec:
  replicas: 1
  selector:
    app: loadbalancer-daemon
  template:
    metadata:
      labels:
        app: loadbalancer-daemon
    spec:
      containers:
      - image: kokhang/loadbalancer-daemon:0.1
        imagePullPolicy: Always
        name: loadbalancer-daemon
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 3306
          hostPort: 3306
      #   securityContext:
      #     privileged: true
      # hostNetwork: true


